ASYMMETRIC_KEY_TYPE_FIELD_NAME: str = "asymmetric_key_type"
ASYMMETRIC_KEY_LENGTH_FIELD_NAME: str = "asymmetric_length"
ASYMMETRIC_KEY_FIELD_NAME: str = "asymmetric_key"
SYMMETRIC_KEY_TYPE_FIELD_NAME: str = "symmetric_key_type"
SYMMETRIC_KEY_LENGTH_FIELD_NAME: str = "symmetric_length"
SYMMETRIC_KEY_FIELD_NAME: str = "symmetric_key"
CONNECTION_MESSAGE: str = "connection"
SESSION_MESSAGE: str = "session"
